#!/usr/bin/env bash
#  Copyright (C) 2026 Aldo Nicolas Bruno
#  SPDX-License-Identifier: Apache-2.0
#
#  adi.gpr withs config/adi2_config.gpr to learn which build profile was
#  chosen. Alire writes that file, but only on `alr build` -- not on
#  `alr exec`, and not at all in a checkout nobody has built yet. Anything
#  that calls gprbuild directly has to make sure it is there first, or the
#  build stops at "imported project file not found".
#
#  Writes only when the file is absent, so Alire's own copy is never
#  replaced by this weaker one. The version is read from alire.toml so the
#  two cannot drift. The profile named here is only a fallback: callers
#  that care pass -XADI_BUILD_PROFILE or export it.
set -u

ROOT="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
CONFIG_GPR="${ROOT}/config/adi2_config.gpr"

[[ -f "${CONFIG_GPR}" ]] && exit 0

CRATE_VERSION="$(sed -n 's/^version *= *"\([^"]*\)".*/\1/p' "${ROOT}/alire.toml" | head -1)"
if [[ -z "${CRATE_VERSION}" ]]; then
  echo "ensure_build_config: no version in ${ROOT}/alire.toml" >&2
  exit 1
fi

mkdir -p "${ROOT}/config"
cat > "${CONFIG_GPR}" <<EOF
--  Generated by tools/ensure_build_config.sh because Alire was not the
--  one building. Alire overwrites this on the next \`alr build\`.
abstract project Adi2_Config is
   Crate_Version := "${CRATE_VERSION}";
   Crate_Name := "adi2";

   type Build_Profile_Kind is ("release", "validation", "development");
   Build_Profile : Build_Profile_Kind := "development";
end Adi2_Config;
EOF

echo "ensure_build_config: wrote ${CONFIG_GPR} (version ${CRATE_VERSION})"
